# Change these first
owner: sfvc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CatamarcaCapital
    url: https://www.catamarcaciudad.gob.ar
  - name: Civitas Juzgado
    url: http://civitas.catamarcaciudad.gob.ar:8080/JUZ_CATA/forms/login.jsp
  - name: Civitas RRHH
    url: http://civitas.catamarcaciudad.gob.ar:8080/GRH_CATA/forms/login.jsp
  - name: Turnero
    url: https://turnos.catamarcacapital.gob.ar/
  - name: Turnero CEL
    url: https://turnos.catamarcacapital.gob.ar/cel/
  - name: Tu bienestar
    url: https://tubienestar.catamarcacapital.gob.ar/solicitudes
  - name: Planos
    url: https://correcciondeplanos.catamarcaciudad.gob.ar/
  - name: Compras
    url: https://compras.catamarcaciudad.gob.ar/
  - name: Empleo
    url: https://beneficiarios.catamarcaciudad.gob.ar/
  - name: Recibos
    url: https://recibos.catamarcaciudad.gob.ar/acceso.php
  - name: Trámites online Juzgado
    url: http://juzgado.catamarcacapital.gob.ar/
  - name: Nodo
    url: https://nodotecnologico.catamarcacapital.edu.ar/
  - name: GIRO
    url: https://giro.catamarcacapital.gob.ar/
  - name: Tu Decision
    url: https://tudecision.catamarcacapital.gob.ar
  - name: Catastro
    url: https://catastro.catamarcaciudad.gob.ar/sfvccatastro/myLogin.php
  - name: Transporte
    url: https://transporte.catamarcacapital.gob.ar/login
  - name: Economía Social
    url: https://economiasocial.catamarcacapital.gob.ar
  - name: PEI
    url: https://planestrategico.catamarcacapital.gob.ar
  - name: Inspecciones
    url: https://inspecciones.catamarcaciudad.gob.ar
  - name: Educación
    url: https://educacion.catamarcaciudad.gob.ar
  - name: Habilitaciones comerciales
    url: https://solicitudes-hc.cc.gob.ar
  - name: Back habilitaciones comerciales
    url: https://solicitudes-hc.cc.gob.ar/admin
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://cc.gob.ar/assets/logo.svg
  name: Status
  introTitle: "Estado de las páginas de Catamrca Capital"
  introMessage: Esta muestra el estado de las páginas y sistemas de la municpalidad de San Fernanod del Valle de Catamarca
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
